export enum ProductsActionType {
  GET_ALL_PRODUCTS_START = 'GET_ALL_PRODUCTS_START',
  GET_ALL_PRODUCTS_ACCEPTED = 'GET_ALL_PRODUCTS_ACCEPTED',
  GET_ALL_PRODUCTS_DENIED = 'GET_ALL_PRODUCTS_DENIED',
  SAVE_ALL_PRODUCTS = 'SAVE_ALL_PRODUCTS',
  CLEAR_ALL_PRODUCTS = 'CLEAR_ALL_PRODUCTS',
}
